### ISSUE TITLE
Make the website responsive for the tablet view.

### ISSUE THREAD

**Issue by ShreyashYewale** [Developer-Students-Clubs-MESCOE/Web-Bootcamp-Portfolio#1]

**Comment by ghost** [comment]
hi, can i be assigned this issue?

**Comment by pratiksha23-github** [comment]
hello, can I contribute to this issue?

**Comment by ShreyashYewale** [comment]
> hello, can I contribute to this issue?

Yes sure you can

**Comment by ShreyashYewale** [comment]
> hi, can i be assigned this issue?

Yes u can contribute.

**Comment by ShreyashYewale** [comment]
> hello, can I contribute to this issue?

Yes u can start working and once fininshed you can make a pull request. If your contribution is correct we will merge it.

**Comment by supsa-ak** [comment]
I think issue is in mobile view not at tablet view

**Comment by supsa-ak** [comment]
Hi, Shreyas 
I have just made a pull request and got to  know that project is not participating in hacktoberfest. This issue is labeled as 'hacktoberfest' but repo is not. I got  this warning 
![image](https://user-images.githubusercontent.com/65620738/137631758-eb0c0218-ecf9-40bb-96f9-a57df64e3c4d.png)
Please try to add repository topic as 'hacktoberfest' or just lable this PR #2 as 'hacktoberfest-accepted'. 
It will really help me a lot 😀

**Comment by ShreyashYewale** [comment]
I have added the label to the pull request.
